spring.application.name=delivery
server.port=3002

spring.datasource.url=jdbc:sqlite:foody.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=a2fedb5f-d95c-4739-8f21-eaea9118a1aa
